### ISSUE TITLE
LineChart.js sends wrong Tooltip information

### ISSUE THREAD

**Issue by flaviomueller** [Beckhoff/TF2000_Server_Samples#3]
When working with the TcHmiLinechart I think I found a bug in the source code for the control in TcHmiLineChart.js

![image](https://user-images.githubusercontent.com/88711651/172777556-a05c5165-bbae-4810-b6c0-36cd7192792b.png)

On the mouse over and mouse hover events the coordinates of x are written to both x and y: `x: __this.__lineGraphData[i][j].x`

**Comment by soberschmidt** [comment]
@flaviomueller Thanks for your feedback. It will be fixed with the next update of the control package (version >= 1.12.758.0)
