### ISSUE TITLE
LetsEncrypt sample breaks with new API that auto register listeners that don't need additional settings

### ISSUE THREAD

**Issue by ZDaulton** [Beckhoff/TF2000_Server_Samples#4]
In some new API version, Shutdown Listener is auto registered when created. This breaks the LetsEncrypt sample with the following error on Init() : 

"Error while initialization: Cannot register listeners of the same type and in the same domain several times. A listener of type 'ITcHmiSrvShutdownListener' is already registered in domain 'LetsEncrypt'."

Two possible work arounds:

1. On Init(), set TcHmiApplication.AutoRegisterListeners to false
2. Remove _shutdownListener.OnShutdown += OnShutdown;

Manually registering OnShutdown allows custom logic to run on shutdown. But with auto register listeners defaulting to true, one cannot add in a custom even handler to run due to OnShutdown implicitly registering. What event handlers are automatically added to simple listeners like Shutdown?

**Comment by mabexte** [comment]
@ZDaulton ShutdownListener has been removed.

**Comment by HolgerJeromin** [comment]
In 3bb8f3834a92850a0a49c3ff9230e8f7484ca496
